import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import Breadcrumb from "@/components/layout/breadcrumb";
import Sidebar from "@/components/layout/sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="vi">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="min-h-screen md:max-h-screen flex flex-col md:flex-row bg-rainy text-white">
					<Sidebar />

					<div className="flex-1">
						<div className="flex flex-col h-full">
							<Breadcrumb />
							<div className="p-4 md:p-6 flex-1 overflow-auto">
								{children}
							</div>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
